# Generated by Django 6.0.5 on 2026-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, default='Case Factory', max_length=255)),
                ('email', models.EmailField(blank=True, default='casefactorycpy@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 9876543210', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='+91 9876543210', max_length=50)),
                ('instagram', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com')),
                ('address', models.TextField(blank=True, default='123 Luxury Street, Fashion City')),
                ('business_hours', models.TextField(blank=True, default='Mon - Sat, 10:00 AM - 8:00 PM')),
                ('google_maps_embed', models.TextField(blank=True, default='')),
            ],
        ),
    ]
