# Generated by Django 6.0.5 on 2026-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_enquiry_template',
            field=models.TextField(blank=True, default="Hello, I'm interested in:\nProduct: {product_name}\nPrice: {product_price}\nCan you provide more details?"),
        ),
    ]
