# Generated by Django 6.0.5 on 2026-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_storesettings_whatsapp_enquiry_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_hero_background',
            field=models.BooleanField(default=False),
        ),
    ]
