# Generated by Django 6.0.5 on 2026-05-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_show_in_hero_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_in_hero_background',
        ),
    ]
