# Generated by Django 6.0.5 on 2026-05-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_show_in_hero_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_hero',
            field=models.BooleanField(default=False),
        ),
    ]
