# Generated by Django 6.0.5 on 2026-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_show_in_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_in_hero',
        ),
        migrations.AddField(
            model_name='product',
            name='new_badge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
