# Generated by Django 6.0.5 on 2026-05-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_show_in_hero_product_new_badge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='theme_color',
            field=models.CharField(default='#7B2EFF', max_length=20),
        ),
    ]
