# Generated by Django 6.0.5 on 2026-05-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_theme_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
