# Generated by Django 6.0.5 on 2026-05-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enquiry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
