# Generated by Django 6.0.5 on 2026-05-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_cancellation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIPaymentApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('gpay', 'Google Pay'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('bhim', 'BHIM UPI'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=200)),
                ('merchant_name', models.CharField(default='Case Factory', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.upipaymentapp'),
        ),
    ]
